pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                echo 'Pulling latest code from GitHub...'
                git branch: 'main', url: 'https://github.com/sowtheswari22/ec2-folder-automation'
            }
        }

        stage('Deploy to /opt') {
            steps {
                echo 'Copying hello.sh to /opt and making it executable'
                sh '''
                    cp ${WORKSPACE}/my-first-pipeline/hello.sh /opt/jenkins/hello.sh
                    chmod +x /opt/jenkins/hello.sh
                '''
            }
        }

        stage('Run Script') {
            steps {
                echo 'Executing the script'
                sh '/opt/hello.txt
            }
        }
    }

    post {
        success {
            echo 'Deployment and execution completed successfully!'
        }
        failure {
            echo 'Deployment or execution failed.'
        }
    }
}

     
