pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                echo 'Code pulled from GitHub'
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(['ec2-key']) {
                    sh """
                    scp -o StrictHostKeyChecking=no hello.sh ubuntu@:/15.207.21.102:opt/hello_world.txt
                    """
                }
            }
        }
    }
}
