pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                echo 'Code pulled from GitHub'
            }
        }

        stage('Deploy to EC2') {
            steps {
                sshagent(['ec2-key']) {
                    // Copy the hello.sh file to EC2
                    sh """
                        scp -o StrictHostKeyChecking=no my-first-pipeline/hello.sh ubuntu@15.207.21.102:/opt/hello.sh
                        ssh -o StrictHostKeyChecking=no ubuntu@15.207.21.102 "chmod +x /opt/hello.sh && /opt/hello.sh"
                    """
                }
            }
        }
    }
}
